// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA7niG3RATQdc9awmqPEkRPjDrP3WyliA',
    appId: '1:573303993251:web:e7b15d533971900795a016',
    messagingSenderId: '573303993251',
    projectId: 'todo-spring-2025-833d9',
    authDomain: 'todo-spring-2025-833d9.firebaseapp.com',
    storageBucket: 'todo-spring-2025-833d9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW9Sih05BAQD2VHNLTijdYkxCzcqzQg5A',
    appId: '1:573303993251:android:a45a66c2c1fee5ae95a016',
    messagingSenderId: '573303993251',
    projectId: 'todo-spring-2025-833d9',
    storageBucket: 'todo-spring-2025-833d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD-Hm-gMJVqnjVCL1Rw42XWUlOhThYIqk',
    appId: '1:573303993251:ios:ee1a0bfd68bd9cdd95a016',
    messagingSenderId: '573303993251',
    projectId: 'todo-spring-2025-833d9',
    storageBucket: 'todo-spring-2025-833d9.firebasestorage.app',
    iosBundleId: 'com.example.todoSpring2025',
  );
}